### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by adrienbrunet** [LCOGT/whatsup#8]
Hi,

There is License.txt and License on the root of the repo. Should we just keep one?
Given that license, should we bother rewriting a shorter version of this license on each file? (at least some of them have a license part at the beginning of the file.)
I feel like it's pointless and make the code less easy to read. The shorter the better. =)

**Comment by zemogle** [comment]
Well spotted! That was a mistake. I've removed the Licence.txt file from the master branch now.

We've chosen the GPL v3 for all of our projects. That means there is a shorter version of the licence at the top of each file with the important stuff in it. :sunglasses:

**Comment by ire-and-curses** [comment]
Hi Adrien,

I understand your point about extra stuff in file headers (I feel the same way). However, this is standard practice (http://www.gnu.org/licenses/gpl-howto.en.html). It makes it harder to externally reuse components of a project without acknowledging the GPL, since you would have to change the file to remove the header. It's also important that we place copyright at the top of each file so that the code is explicitly identifies us as the rights holders for the license.
